"""Generate original, modular static meshes for the cosmetic sculling rower.

All dimensions are centimetres. Torso uses the existing torso-component origin;
arm and leg segments run along local +X from 0 to 100 for pose-driven scaling.
The shoes use the ankle as their origin and point toward the bow (+X).
"""

from __future__ import annotations

import math
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "Content" / "Boat" / "Source"
SIDES = 12


class Mesh:
	def __init__(self) -> None:
		self.vertices: list[tuple[float, float, float]] = []
		self.faces: list[tuple[str, tuple[int, ...]]] = []

	def vertex(self, x: float, y: float, z: float) -> int:
		self.vertices.append((x, y, z))
		return len(self.vertices)

	def face(self, material: str, *indices: int) -> None:
		self.faces.append((material, indices))

	def rings_z(self, stations: list[tuple[float, float, float, float]], materials: list[str]) -> None:
		"""Join (height, centre X, X radius, Y radius) rings into a closed shell."""
		rings = [
			[self.vertex(center_x + radius_x * math.cos(2 * math.pi * side / SIDES),
						 radius_y * math.sin(2 * math.pi * side / SIDES), height)
			 for side in range(SIDES)]
			for height, center_x, radius_x, radius_y in stations
		]
		for ring_index, (before, after) in enumerate(zip(rings, rings[1:])):
			for side in range(SIDES):
				next_side = (side + 1) % SIDES
				self.face(materials[ring_index], before[side], before[next_side],
						  after[next_side], after[side])
		self.face(materials[0], *reversed(rings[0]))
		self.face(materials[-1], *rings[-1])

	def rings_x(self, stations: list[tuple[float, float, float, float, float]], materials: list[str]) -> None:
		"""Join (X, centre Y, centre Z, Y radius, Z radius) rings into a closed shell."""
		rings = [
			[self.vertex(x, center_y + radius_y * math.cos(2 * math.pi * side / SIDES),
						 center_z + radius_z * math.sin(2 * math.pi * side / SIDES))
			 for side in range(SIDES)]
			for x, center_y, center_z, radius_y, radius_z in stations
		]
		for ring_index, (before, after) in enumerate(zip(rings, rings[1:])):
			for side in range(SIDES):
				next_side = (side + 1) % SIDES
				self.face(materials[ring_index], before[side], before[next_side],
						  after[next_side], after[side])
		self.face(materials[0], *reversed(rings[0]))
		self.face(materials[-1], *rings[-1])

	def write(self, name: str, colors: dict[str, tuple[float, float, float]]) -> None:
		SOURCE.mkdir(parents=True, exist_ok=True)
		path = SOURCE / f"{name}.obj"
		lines = [f"# Original VIR rower part; generated by Scripts/build_rower_character_meshes.py",
				 f"# Units: centimetres. Object: {name}", f"mtllib {name}.mtl", f"o {name}"]
		lines.extend(f"v {x:.5f} {y:.5f} {z:.5f}" for x, y, z in self.vertices)
		material = None
		for face_material, indices in self.faces:
			if face_material != material:
				material = face_material
				lines.append(f"usemtl {material}")
			lines.append("f " + " ".join(map(str, indices)))
		path.write_text("\n".join(lines) + "\n", encoding="utf-8")
		mtl = ["# Original VIR rower palette; no bitmap dependencies"]
		for color_name, (red, green, blue) in colors.items():
			mtl.extend((f"newmtl {color_name}", f"Kd {red:.4f} {green:.4f} {blue:.4f}", ""))
		path.with_suffix(".mtl").write_text("\n".join(mtl), encoding="utf-8")
		print(f"{path}: {len(self.vertices)} vertices, {len(self.faces)} faces")


def torso() -> None:
	mesh = Mesh()
	mesh.rings_z([
		(-37, 0, 11, 15), (-31, 0, 15, 18), (-8, 0, 17, 20),
		(14, -2, 19, 25), (28, -3, 18, 24), (35, -1, 10, 12),
		(39, 0, 7, 8),
	], ["RowerJersey"] * 5 + ["RowerCollar"])
	# The neck and featureless head use a quiet, unbranded silhouette.
	mesh.rings_z([
		(38, 2, 6, 7), (45, 3, 7, 8), (48, 5, 10, 10),
		(59, 7, 11, 11), (68, 7, 8, 9), (72, 6, 3, 4),
	], ["RowerSkin"] * 5)
	mesh.rings_z([(63, 6, 9, 10), (68, 6, 9, 10), (73, 5, 4, 5)],
				 ["RowerCap", "RowerCap"])
	mesh.write("SM_RowerTorso", {
		"RowerJersey": (0.12, 0.31, 0.43), "RowerCollar": (0.04, 0.10, 0.15),
		"RowerSkin": (0.55, 0.37, 0.28), "RowerCap": (0.08, 0.11, 0.14),
	})


def arm() -> None:
	mesh = Mesh()
	mesh.rings_x([
		(0, 0, 0, 8, 9), (15, 0, 0, 8, 8), (43, 0, 2, 6, 6),
		(55, 0, 3, 5.5, 5.5), (82, 0, 1, 4.5, 4.5), (93, 0, 0, 5, 4.5),
		(100, 0, 0, 4, 4),
	], ["RowerSleeve"] * 3 + ["RowerForearm", "RowerForearm", "RowerHand"])
	mesh.write("SM_RowerArm", {
		"RowerSleeve": (0.12, 0.31, 0.43),
		"RowerForearm": (0.55, 0.37, 0.28), "RowerHand": (0.49, 0.31, 0.23),
	})


def leg() -> None:
	mesh = Mesh()
	mesh.rings_x([
		(0, 0, 0, 11, 10), (18, 0, 1, 11, 10), (46, 0, 3, 9, 9),
		(73, 0, 2, 7, 7), (100, 0, 0, 6, 6),
	], ["RowerPants"] * 4)
	mesh.write("SM_RowerLeg", {"RowerPants": (0.08, 0.13, 0.18)})


def shoe() -> None:
	mesh = Mesh()
	mesh.rings_x([
		(0, 0, 0, 6, 8), (5, 0, -2, 8, 7), (22, 0, -4, 10, 5),
		(33, 0, -4, 8, 4), (38, 0, -3, 2, 2),
	], ["RowerShoe"] * 4)
	mesh.write("SM_RowerShoe", {"RowerShoe": (0.025, 0.035, 0.045)})


def main() -> None:
	torso()
	arm()
	leg()
	shoe()


if __name__ == "__main__":
	main()
