"""Generate the original single-scull hull imported as SM_ScullHull.

Coordinates are centimetres in boat-local space: +X is the bow, Y is beam,
and Z is height. The existing BoatRoot is the origin. The mesh is cosmetic:
it has no collision and its waterline is approximately Z=-30 cm.
"""

from __future__ import annotations

import math
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DESTINATION = ROOT / "Content" / "Boat" / "Source" / "SM_ScullHull.obj"
STATIONS = [
	(-420, 1.2, -20, 39), (-390, 7, -30, 47), (-320, 17, -38, 51),
	(-220, 25, -43, 54), (-145, 29, -44, 55), (-70, 31, -44, 55),
	(0, 32, -44, 55), (70, 31, -44, 55), (145, 29, -44, 55),
	(220, 25, -43, 54), (320, 17, -38, 51), (390, 7, -30, 47),
	(420, 1.2, -20, 39),
]


class Mesh:
	def __init__(self) -> None:
		self.vertices: list[tuple[float, float, float]] = []
		self.faces: list[tuple[str, tuple[int, ...]]] = []

	def vertex(self, x: float, y: float, z: float) -> int:
		self.vertices.append((x, y, z))
		return len(self.vertices)

	def face(self, material: str, *indices: int) -> None:
		self.faces.append((material, indices))

	def quad(self, material: str, a: int, b: int, c: int, d: int) -> None:
		self.face(material, a, b, c, d)

	def rod(self, start: tuple[float, float, float], end: tuple[float, float, float], radius: float, material: str) -> None:
		axis = tuple(b - a for a, b in zip(start, end))
		length = math.sqrt(sum(value * value for value in axis))
		unit = tuple(value / length for value in axis)
		basis = (1.0, 0.0, 0.0) if abs(unit[0]) < 0.9 else (0.0, 0.0, 1.0)
		cross = (unit[1] * basis[2] - unit[2] * basis[1],
				 unit[2] * basis[0] - unit[0] * basis[2],
				 unit[0] * basis[1] - unit[1] * basis[0])
		norm = math.sqrt(sum(value * value for value in cross))
		u = tuple(value / norm for value in cross)
		v = (unit[1] * u[2] - unit[2] * u[1],
			 unit[2] * u[0] - unit[0] * u[2],
			 unit[0] * u[1] - unit[1] * u[0])
		rings = []
		for center in (start, end):
			rings.append([self.vertex(*(center[k] + radius * (math.cos(2 * math.pi * side / 8) * u[k]
				+ math.sin(2 * math.pi * side / 8) * v[k]) for k in range(3))) for side in range(8)])
		for side in range(8):
			next_side = (side + 1) % 8
			self.quad(material, rings[0][side], rings[0][next_side], rings[1][next_side], rings[1][side])
		self.face(material, *reversed(rings[0]))
		self.face(material, *rings[1])

	def write(self, destination: Path) -> None:
		destination.parent.mkdir(parents=True, exist_ok=True)
		lines = ["# Original VIR single-scull hull; generated by Scripts/build_scull_hull_mesh.py",
				 "# Units: centimetres. +X: bow. BoatRoot is the origin.",
				 "mtllib SM_ScullHull.mtl", "o SM_ScullHull"]
		lines.extend(f"v {x:.5f} {y:.5f} {z:.5f}" for x, y, z in self.vertices)
		material = None
		for face_material, indices in self.faces:
			if face_material != material:
				material = face_material
				lines.append(f"usemtl {material}")
			lines.append("f " + " ".join(map(str, indices)))
		destination.write_text("\n".join(lines) + "\n", encoding="utf-8")
		materials = {"Shell": (0.84, 0.88, 0.91), "Sheer": (0.07, 0.15, 0.24),
					 "Deck": (0.74, 0.79, 0.82), "Cockpit": (0.025, 0.035, 0.045),
					 "Rigger": (0.48, 0.53, 0.57)}
		mtl = ["# Original VIR hull colors; no bitmap dependencies"]
		for name, (red, green, blue) in materials.items():
			mtl.extend((f"newmtl {name}", f"Kd {red:.4f} {green:.4f} {blue:.4f}", ""))
		destination.with_suffix(".mtl").write_text("\n".join(mtl), encoding="utf-8")


def build() -> Mesh:
	mesh = Mesh()
	rings: list[list[int]] = []
	for x, width, keel, top in STATIONS:
		profile = [(-width, top), (-width * 0.98, top - 6),
				   (-width * 0.94, 6), (-width * 0.67, keel + 12), (0, keel),
				   (width * 0.67, keel + 12), (width * 0.94, 6),
				   (width * 0.98, top - 6), (width, top)]
		rings.append([mesh.vertex(x, y, z) for y, z in profile])
	for before, after in zip(rings, rings[1:]):
		for edge in range(8):
			material = "Sheer" if edge in (0, 7) else "Shell"
			mesh.quad(material, before[edge], before[edge + 1], after[edge + 1], after[edge])
	mesh.face("Shell", *reversed(rings[0]))
	mesh.face("Shell", *rings[-1])

	# Separate deck panels stop at the cockpit; the dark, lowered floor and
	# vertical coamings keep the opening legible from the chase camera.
	for index, (before, after) in enumerate(zip(rings, rings[1:])):
		x0, width0, _, top0 = STATIONS[index]
		x1, width1, _, top1 = STATIONS[index + 1]
		if x0 >= -145 and x1 <= 145:
			inner_width = min(19.0, width0 - 3.0, width1 - 3.0)
			p0 = mesh.vertex(x0, -inner_width, top0)
			p1 = mesh.vertex(x1, -inner_width, top1)
			q0 = mesh.vertex(x0, inner_width, top0)
			q1 = mesh.vertex(x1, inner_width, top1)
			floor_p0 = mesh.vertex(x0, -inner_width, 29)
			floor_p1 = mesh.vertex(x1, -inner_width, 29)
			floor_q0 = mesh.vertex(x0, inner_width, 29)
			floor_q1 = mesh.vertex(x1, inner_width, 29)
			mesh.quad("Deck", before[0], after[0], p1, p0)
			mesh.quad("Deck", q0, q1, after[8], before[8])
			mesh.quad("Cockpit", floor_p0, floor_p1, floor_q1, floor_q0)
			mesh.quad("Cockpit", p0, p1, floor_p1, floor_p0)
			mesh.quad("Cockpit", floor_q0, floor_q1, q1, q0)
			if x0 == -145:
				mesh.quad("Cockpit", p0, floor_p0, floor_q0, q0)
			if x1 == 145:
				mesh.quad("Cockpit", floor_p1, p1, q1, floor_q1)
		else:
			mesh.quad("Deck", before[0], after[0], after[8], before[8])

	# Outriggers share the mesh and reach the existing oarlock positions.
	for side in (-1, 1):
		for x in (-55, 55):
			mesh.rod((x, side * 27, 51), (0, side * 95, 101), 1.7, "Rigger")
		mesh.rod((0, side * 95, 94), (0, side * 95, 109), 3.2, "Sheer")
	return mesh


def main() -> None:
	mesh = build()
	mesh.write(DESTINATION)
	print(f"{DESTINATION}: {len(mesh.vertices)} vertices, {len(mesh.faces)} faces")


if __name__ == "__main__":
	main()
