"""Generate the original, low-poly sculling oar imported as SM_ScullOar.

The oarlock is the origin. Local +X runs toward the blade; dimensions are cm.
The source OBJ is kept so the editor asset can be rebuilt without hand edits.
"""

from __future__ import annotations

import math
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DESTINATION = ROOT / "Content" / "Boat" / "Source" / "SM_ScullOar.obj"
SIDES = 12


class Mesh:
	def __init__(self) -> None:
		self.vertices: list[tuple[float, float, float]] = []
		self.faces: list[tuple[str, tuple[int, ...]]] = []

	def vertex(self, x: float, y: float, z: float) -> int:
		self.vertices.append((x, y, z))
		return len(self.vertices)

	def face(self, material: str, *indices: int) -> None:
		self.faces.append((material, indices))

	def lathe(self, stations: list[tuple[float, float]], material: str) -> None:
		rings: list[list[int]] = []
		for x, radius in stations:
			rings.append([
				self.vertex(x, radius * math.cos(2 * math.pi * side / SIDES),
							   radius * math.sin(2 * math.pi * side / SIDES))
				for side in range(SIDES)
			])
		for before, after in zip(rings, rings[1:]):
			for side in range(SIDES):
				following = (side + 1) % SIDES
				self.face(material, before[side], before[following], after[following], after[side])
		self.face(material, *reversed(rings[0]))
		self.face(material, *rings[-1])

	def blade(self) -> None:
		# A thin spoon with rounded shoulders, a wide working face, and upturned edges.
		stations = [(156, 1.5), (164, 5.0), (174, 8.5), (190, 10.5),
					(207, 10.5), (218, 8.0), (224, 2.5)]
		profiles: list[tuple[list[int], list[int]]] = []
		for x, width in stations:
			top: list[int] = []
			bottom: list[int] = []
			for fraction in (-1.0, -0.5, 0.0, 0.5, 1.0):
				y = width * fraction
				# The blade is slightly cupped and tapers into the cylindrical shaft.
				crown = -1.2 + 1.7 * fraction * fraction
				top.append(self.vertex(x, y, crown))
				bottom.append(self.vertex(x, y, crown - 1.2))
			profiles.append((top, bottom))
		for (previous_top, previous_bottom), (next_top, next_bottom) in zip(profiles, profiles[1:]):
			for strip in range(4):
				self.face("Blade", previous_top[strip], next_top[strip],
						  next_top[strip + 1], previous_top[strip + 1])
				self.face("Blade", previous_bottom[strip + 1], next_bottom[strip + 1],
						  next_bottom[strip], previous_bottom[strip])
			self.face("Blade", previous_top[0], previous_bottom[0],
					  next_bottom[0], next_top[0])
			self.face("Blade", previous_bottom[-1], previous_top[-1],
					  next_top[-1], next_bottom[-1])
		for first, reverse in ((profiles[0], True), (profiles[-1], False)):
			top, bottom = first
			for strip in range(4):
				indices = (top[strip], top[strip + 1], bottom[strip + 1], bottom[strip])
				self.face("Blade", *(reversed(indices) if reverse else indices))

	def write(self, destination: Path) -> None:
		destination.parent.mkdir(parents=True, exist_ok=True)
		lines = ["# Original VIR sculling oar; generated by Scripts/build_scull_oar_mesh.py",
				 "# Units: centimetres. Origin: oarlock. +X: outboard blade.",
				 "mtllib SM_ScullOar.mtl",
				 "o SM_ScullOar"]
		lines.extend(f"v {x:.5f} {y:.5f} {z:.5f}" for x, y, z in self.vertices)
		material = None
		for face_material, indices in self.faces:
			if face_material != material:
				material = face_material
				lines.append(f"usemtl {material}")
			lines.append("f " + " ".join(map(str, indices)))
		destination.write_text("\n".join(lines) + "\n", encoding="utf-8")
		materials = {
			"Grip": (0.06, 0.07, 0.08),
			"Shaft": (0.78, 0.82, 0.84),
			"Collar": (0.12, 0.15, 0.17),
			"Blade": (0.72, 0.07, 0.06),
		}
		mtl = ["# Original VIR sculling oar colors; no bitmap dependencies"]
		for name, (red, green, blue) in materials.items():
			mtl.extend((f"newmtl {name}", f"Kd {red:.4f} {green:.4f} {blue:.4f}", ""))
		destination.with_suffix(".mtl").write_text("\n".join(mtl), encoding="utf-8")


def main() -> None:
	mesh = Mesh()
	mesh.lathe([(-90, 1.8), (-86, 2.2), (-68, 2.3), (-52, 1.9)], "Grip")
	mesh.lathe([(-52, 1.9), (-25, 2.2), (-8, 2.6), (12, 2.5),
				(75, 2.0), (130, 1.6), (158, 1.3)], "Shaft")
	mesh.lathe([(-9, 2.7), (-7, 3.4), (7, 3.4), (9, 2.7)], "Collar")
	mesh.blade()
	mesh.write(DESTINATION)
	print(f"{DESTINATION}: {len(mesh.vertices)} vertices, {len(mesh.faces)} faces")


if __name__ == "__main__":
	main()
